name: .NET Core Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Wavect.TariffComparison/Wavect.TariffComparison.sln  --verbosity normal
    - name: Build
      run: dotnet build  ./Wavect.TariffComparison/Wavect.TariffComparison.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test  ./Wavect.TariffComparison/Wavect.TariffComparison.sln --no-restore --verbosity normal
